tasks:
  - init: npm install --prefix servidor
    command: npm start --prefix servidor
  - name: servidor
    init: Npm install
    command: npm start

ports:
  - port: 3000
    onOpen: open-browser
